#!/bin/bash
# SPDX-License-Identifier: MIT-0

set -euxo pipefail

package_url=

while [ "${1:-}" != "" ]; do
  case "$1" in
    --package-url)
      shift
      if [[ $# -eq 0 ]]; then
        echo 'No argument specified for --package-url' >&2
        exit 1
      fi
      package_url="$1"
      ;;
    *)
      echo 'Invalid command line argument' >&2
      exit 1
  esac
  shift
done

export DEBIAN_FRONTEND=noninteractive

readonly apt_install=(
  apt-get
  -o Acquire::Retries=4
  -o Dpkg::Use-Pty=0
  -qy --no-install-recommends install
)

apt-get -qq update || (sleep 30; apt-get -qq update)
"${apt_install[@]}" \
  build-essential \
  ca-certificates \
  cmake \
  gnupg \
  lsb-release \
  python3-dev \
  wget

if [[ ! -z "${package_url}" ]]; then
  # Install a custom Drake package if specified.
  wget -O drake.deb ${package_url}
  trap 'rm -f drake.deb' EXIT

  "${apt_install[@]}" ./drake.deb
else
  # Otherwise, install the latest released version.
  readonly codename="$(lsb_release -cs)"

  wget -qO- --retry-connrefused https://drake-apt.csail.mit.edu/drake.asc \
    | gpg --dearmor - > /etc/apt/trusted.gpg.d/drake.gpg
  echo "deb [arch=amd64] https://drake-apt.csail.mit.edu/${codename} ${codename} main" \
    > /etc/apt/sources.list.d/drake.list

  apt-get -qq update || (sleep 30; apt-get -qq update)
  "${apt_install[@]}" drake-dev
fi
