#!/bin/bash
# SPDX-License-Identifier: MIT-0

set -euxo pipefail

# Use what we downloaded to drake_bazel_external_legacy/drake,
# rather than the URL to the latest Drake master branch
# found in drake_bazel_external_legacy/WORKSPACE.
export EXAMPLES_LOCAL_DRAKE_PATH=$(realpath drake)

# Pass along the compiler version to Drake, which enables
# compiler warning suppression for gcc 13 (as suggested in
# drake_bazel_external_legacy/.bazelrc).
gcc_flag="--@drake//tools/cc_toolchain:compiler_major="
gcc_flag="${gcc_flag}$(gcc -dumpversion | cut -d. -f1)"

bazel version
bazel test "${gcc_flag}" //...
