#!/bin/bash
# SPDX-License-Identifier: MIT-0

set -euxo pipefail

# Use what we downloaded to drake_bazel_external_legacy/drake,
# rather than the URL to the latest Drake master branch
# found in drake_bazel_external_legacy/WORKSPACE.
export EXAMPLES_LOCAL_DRAKE_PATH=$(realpath drake)
trap 'unset EXAMPLES_LOCAL_DRAKE_PATH' EXIT

bazel version
bazel test //...
