#!/bin/zsh
# SPDX-License-Identifier: MIT-0

set -euxo pipefail

# Installs a /usr/local/bin/bazel symlink that conflicts with that installed by
# the bazel formula in Homebrew.
brew uninstall -f bazelisk

git clone --filter=blob:none https://github.com/RobotLocomotion/drake.git
./setup/mac/install_prereqs.sh
