#!/bin/zsh
# SPDX-License-Identifier: MIT-0

set -euxo pipefail

# Installs a /usr/local/bin/bazel symlink that conflicts with that installed by
# the bazel formula in Homebrew.
brew uninstall -f bazelisk

./scripts/continuous_integration/common/mac
