#!/bin/zsh
# SPDX-License-Identifier: MIT-0

set -euxo pipefail

# Installs a /usr/local/bin/bazel symlink that conflicts with that installed by
# the bazel formula in Homebrew.
brew uninstall -f bazelisk

if [[ ! -d /opt/drake ]]; then
  sudo mkdir -p /opt/drake
  sudo chmod g+rwx /opt/drake
  sudo chown "${USER}" /opt/drake
  sudo chgrp admin /opt/drake
fi

# Install Drake dependencies.
curl -o drake.tar.gz https://drake-packages.csail.mit.edu/drake/nightly/drake-latest-mac-arm64.tar.gz
trap 'rm -f drake.tar.gz' EXIT
tar -xf drake.tar.gz -C /opt

# Show version for debugging; use echo for newline / readability.
echo -e "\ndrake VERSION.TXT: $(cat /opt/drake/share/doc/drake/VERSION.TXT)\n"

./opt/drake/share/drake/setup/mac/install_prereqs.sh
