# SPDX-License-Identifier: MIT-0

---
name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *'
concurrency:
  # Cancel previous CI runs when additional commits are added to a pull request.
  # This will not cancel CI runs associated with `schedule` or `push`.
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  ros_humble_ament_cmake_installed:
      name: ros 2 humble
      runs-on: ubuntu-latest
      container: ubuntu:jammy
      steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: setup
          working-directory: drake_ament_cmake_installed
          run: .github/ros_humble_setup
          shell: bash
        - name: ament_cmake_installed build and test
          working-directory: drake_ament_cmake_installed
          run: .github/ci_build_test
          shell: bash
