#!/bin/bash

# Copyright (c) 2020, Massachusetts Institute of Technology.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of the copyright holder nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

set -euxo pipefail

ros_foxy=0
ros_noetic=0

while [ "${1:-}" != "" ]; do
  case "$1" in
    --ros-foxy)
      ros_foxy=1
      ;;
    --ros-noetic)
      ros_noetic=1
      ;;
    *)
      echo 'Invalid command line argument' >&2
      exit 1
  esac
  shift
done

if [[ "${EUID:-}" -ne 0 ]]; then
  echo 'This script must be run as root' >&2
  exit 2
fi

apt-get update
apt-get install --no-install-recommends lsb-release

if [[ "$(lsb_release -sc)" != 'focal' ]]; then
  echo 'This script requires Ubuntu 20.04 (Focal Fossa)' >&2
  exit 3
fi

apt-get install --no-install-recommends $(cat <<EOF
  ca-certificates
  wget
EOF
)

wget -O drake.tar.gz \
  https://drake-packages.csail.mit.edu/drake/nightly/drake-latest-focal.tar.gz
trap 'rm -f drake.tar.gz' EXIT
tar -xf drake.tar.gz -C /opt

# Show version for debugging; use echo for newline / readability.
echo -e "\ndrake VERSION.TXT: $(cat /opt/drake/share/doc/drake/VERSION.TXT)\n"

/opt/drake/share/drake/setup/install_prereqs

apt-get install --no-install-recommends gnupg

apt-key adv --fetch-keys https://bazel.build/bazel-release.pub.gpg
echo 'deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8' \
  > /etc/apt/sources.list.d/bazel.list

# TODO(drake#17763):  Bazel is pinned here because Bazel 5.3.0 broke the way
# we do LCM builds.  This should be reverted when Bazel fixes the problem or
# when Drake finds a workaround to it.
apt-get update
apt-get install --no-install-recommends $(cat <<EOF
  bazel-5.2.0
  clang-format-12
  cmake
  coinor-libclp-dev
  coinor-libcoinutils-dev
  coinor-libipopt-dev
  default-jdk
  file
  gfortran
  git
  libblas-dev
  libbz2-dev
  libclang-12-dev
  libdouble-conversion-dev
  libexpat1-dev
  libgflags-dev
  libgl-dev
  libglew-dev
  libglib2.0-dev
  libglx-dev
  libjpeg-turbo8-dev
  libjsoncpp-dev
  liblapack-dev
  liblz4-dev
  liblzma-dev
  libmsgpack-dev
  libmumps-seq-dev
  libnlopt-cxx-dev
  libopengl-dev
  libpng-dev
  libsuitesparse-dev
  libtiff-dev
  libtinyxml-dev
  libtool
  libx11-dev
  libxml2-dev
  locales
  ocl-icd-opencl-dev
  opencl-headers
  openssh-client
  patch
  patchelf
  pkg-config
  python-is-python3
  python3-all-dev
  python3-semantic-version
  zlib1g-dev
EOF
)
# Symlink "bazel" to the pinned version.  TODO(drake#17763): Don't do this.
ln -s /usr/bin/bazel-5.2.0 /usr/local/bin/bazel

locale-gen en_US.UTF-8

if [[ ${ros_foxy} -eq 1 ]]; then
  apt-key adv --fetch-keys \
    https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc
  echo 'deb http://packages.ros.org/ros2/ubuntu focal main' \
    > /etc/apt/sources.list.d/ros2-latest.list

  apt-get update
  apt-get install --no-install-recommends $(cat <<EOF
    python3-colcon-common-extensions
    ros-foxy-ament-cmake
    ros-foxy-ament-cmake-gtest
    ros-foxy-ament-cmake-lint-cmake
    ros-foxy-ament-cmake-xmllint
    ros-foxy-ament-lint-auto
EOF
  )
fi

if [[ ${ros_noetic} -eq 1 ]]; then
  apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 \
    --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
  echo 'deb http://packages.ros.org/ros/ubuntu focal main' \
    > /etc/apt/sources.list.d/ros-latest.list

  apt-get update
  apt-get install --no-install-recommends ros-noetic-catkin
fi



if [[ ${ros_foxy} -ne 1 && ${ros_noetic} -ne 1 ]]; then
  apt-get install --no-install-recommends $(cat <<EOF
  catkin
  python3-pkg-resources
EOF
  )
fi
