#!/bin/bash
# SPDX-License-Identifier: MIT-0

set -euxo pipefail

# Use what we installed to $HOME/drake,
# rather than the URL to the most recent nightly release
# found in drake_bazel_download/MODULE.bazel.
drake_override_flag="--override_repository=+_repo_rules2+drake=$HOME/drake"

# Setup $HOME/drake as a Bazel workspace via
# BUILD and WORKSPACE files.
ln -sf $(realpath drake.BUILD.bazel) "$HOME/drake/BUILD.bazel"
touch "$HOME/drake/WORKSPACE.bazel"

bazel version
bazel test "${drake_override_flag}" //...
