#!/bin/bash
# SPDX-License-Identifier: MIT-0

set -eo pipefail

# AMENT_TRACE_SETUP_FILES and other variables are unbound.

if [[ -f /opt/ros/humble/setup.bash ]]; then
  source /opt/ros/humble/setup.bash
fi

set -xu

cmake --version

colcon build
colcon test

chmod -R a+w build install log || true
rm -rf build install log
