#!/bin/bash
# SPDX-License-Identifier: MIT-0

set -euxo pipefail

cmake --version

pushd drake_cmake_external

mkdir build
pushd build

export LD_LIBRARY_PATH="${PWD}/install/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"

cmake ..
make

cd drake_external_examples
ctest -V .

popd

chmod -R a+w build || true
rm -rf build

popd
