#!/bin/bash
# SPDX-License-Identifier: MIT-0

set -euxo pipefail

sudo ./drake_cmake_external/.github/ubuntu_setup

cat > "${HOME}/.bazelrc" << EOF
startup --output_user_root=${WORKSPACE}/_bazel_${USER}
test --color=yes
test --keep_going
EOF
