#!/bin/bash
# SPDX-License-Identifier: MIT-0

set -euxo pipefail

if [[ "${EUID:-}" -ne 0 ]]; then
  echo 'This script must be run as root' >&2
  exit 2
fi

echo 'APT::Acquire::Retries "4";' > /etc/apt/apt.conf.d/80-acquire-retries
echo 'APT::Get::Assume-Yes "true";' > /etc/apt/apt.conf.d/90-get-assume-yes

export DEBIAN_FRONTEND='noninteractive'

apt-get update
apt-get install --no-install-recommends lsb-release

if [[ "$(lsb_release -sc)" != 'noble' ]]; then
  echo 'This script requires Ubuntu 24.04 (Noble)' >&2
  exit 3
fi
