#!/bin/bash
# SPDX-License-Identifier: MIT-0

set -euxo pipefail

maybe_sudo=
if [[ "${EUID}" -ne 0 ]]; then
  maybe_sudo=sudo
fi

case "$OSTYPE" in
    darwin*)
    # Mac-specific installations
    brew install pipx
    ;;

    linux*)
    # Ubuntu-specific installations
    # See https://github.com/RobotLocomotion/drake/blob/master/tools/wheel/content/INSTALLATION
    # for a complete list of the required libraries to be installed.
    ${maybe_sudo} apt-get update
    ${maybe_sudo} apt-get install --no-install-recommends $(cat <<EOF
      libegl1
      libglib2.0-0
      libsm6
      libx11-6
      pipx
      python3
EOF
    )
    ;;
esac

# Install poetry
pipx install poetry
pipx ensurepath
# Update PATH on Linux in order to run the next steps
if [[ "$OSTYPE" == "linux"* ]]; then
  source $HOME/.profile
fi

# If a version of Python other than the default (3) is provided,
# enforce that poetry use that version.
PYTHON_VERSION=${1:-'3'}
echo "Creating poetry environment with python${PYTHON_VERSION}"
if [[ "$PYTHON_VERSION" != "3" ]]; then
  poetry env use $PYTHON_VERSION
fi

# Install poetry dependencies
poetry install
