#!/bin/bash

# SPDX-License-Identifier: MIT-0

set -euxo pipefail

maybe_sudo=
if [[ "${EUID}" -ne 0 ]]; then
  maybe_sudo=sudo
fi

${maybe_sudo} apt-get install --no-install-recommends $(cat <<EOF
  wget
EOF
)

# Download the drake source
wget -O drake.tar.gz \
  https://github.com/RobotLocomotion/drake/archive/master.tar.gz
trap 'rm -f drake.tar.gz' EXIT

# Setup script
tar -xf drake.tar.gz

# Install the source prereqs
drake-master/setup/install_prereqs
