#!/bin/bash

# Copyright (c) 2017, Massachusetts Institute of Technology.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of the Massachusetts Institute of Technology nor the names
#   of its contributors may be used to endorse or promote products derived from
#   this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE MASSACHUSETTS INSTITUTE OF TECHNOLOGY AND
# CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT
# NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE MASSACHUSETTS
# INSTITUTE OF TECHNOLOGY OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
# OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
# EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

set -euo pipefail

if [[ "${EUID}" -ne 0 ]]; then
  echo 'This script must be run as root' >&2
  exit 1
fi

apt-get update -qq
apt-get install --no-install-recommends $(tr '\n' ' ' <<EOF
curl
software-properties-common
EOF
)

add-apt-repository -s 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
curl https://bazel.build/bazel-release.pub.gpg | apt-key add -

apt-get update -qq
apt-get install --no-install-recommends $(tr '\n' ' ' <<EOF
bazel
ca-certificates
cmake
coinor-libipopt-dev
g++
git
libboost-all-dev
libexpat1
libfreetype6
libglib2.0-dev
libglu1-mesa-dev
libhdf5-10
libjpeg8
libjsoncpp1
liblapack-dev
liblz4-dev
libnetcdf-c++4
libnetcdf11
libogg0
libpng-dev
libqt4-opengl
libtheora0
libtiff5
libtinyxml-dev
libtinyxml2-dev
libtool
libxml2
libxt6
make
mesa-common-dev
openjdk-8-jdk
openssh-client
pkg-config
python-dev
python-lxml
python-numpy
python-scipy
python-yaml
zlib1g-dev
EOF
)
