#!/bin/bash

# SPDX-License-Identifier: MIT-0

set -euxo pipefail

sudo apt-get install --no-install-recommends $(cat <<EOF
  wget
EOF
)

# Download the drake source
wget -O drake.tar.gz \
  https://github.com/RobotLocomotion/drake/archive/master.tar.gz
trap 'rm -f drake.tar.gz' EXIT

# Setup script
tar -xf drake.tar.gz

# Install the source prereqs
sudo drake-master/setup/ubuntu/install_prereqs.sh
