#!/bin/bash
# SPDX-License-Identifier: MIT-0

set -euxo pipefail

setup_env_args=()

while [ "${1:-}" != "" ]; do
  case "$1" in
    --wheel-experimental-url)
      shift
      if [[ $# -eq 0 ]]; then
        echo 'No argument specified for --wheel-experimental-url' >&2
        exit 1
      fi
      setup_env_args=(--wheel-experimental-url $1)
      ;;
    --python-version)
      shift
      if [[ $# -eq 0 ]]; then
        echo 'No argument specified for --python-version' >&2
        exit 1
      fi
      setup_env_args+=(--python-version $1)
      ;;
    *)
      echo 'Invalid command line argument' >&2
      exit 1
  esac
  shift
done

maybe_sudo=
if [[ "${EUID}" -ne 0 ]]; then
  maybe_sudo=sudo
fi

# Ubuntu-specific installations
# See https://github.com/RobotLocomotion/drake/blob/master/tools/wheel/content/INSTALLATION
# for a complete list of the required libraries to be installed.
${maybe_sudo} apt-get update
${maybe_sudo} apt-get install --no-install-recommends $(cat <<EOF
  libegl1
  libglib2.0-0
  libsm6
  libx11-6
  python3
  python3-venv
EOF
)

setup/setup_env "${setup_env_args[@]}"
