#!/bin/bash
# SPDX-License-Identifier: MIT-0

set -euxo pipefail

wheel_url=
python_version='3'

while [ "${1:-}" != "" ]; do
  case "$1" in
    --wheel-url)
      shift
      if [[ $# -eq 0 ]]; then
        echo 'No argument specified for --wheel-url' >&2
        exit 1
      fi
      wheel_url="$1"
      ;;
    --python-version)
      shift
      if [[ $# -eq 0 ]]; then
        echo 'No argument specified for --python-version' >&2
        exit 1
      fi
      python_version="$1"
      ;;
    *)
      echo 'Invalid command line argument' >&2
      exit 1
  esac
  shift
done

echo "Creating virtual environment with python${python_version}"
"python${python_version}" -m venv env
# Install from requirements.txt, which currently only includes drake.
"env/bin/pip$python_version" install -r requirements.txt

# Use custom wheels if specified.
if [[ ! -z "${wheel_url}" ]]; then
  "env/bin/pip$python_version" install "${wheel_url}"
fi
