#!/bin/bash
# SPDX-License-Identifier: MIT-0

set -euxo pipefail

cmake --version

mkdir build
pushd build

cmake -DCMAKE_PREFIX_PATH=/opt/drake "$@" ..
make
ctest -V .

popd

chmod -R a+w build || true
rm -rf build

popd
