#!/bin/bash
# SPDX-License-Identifier: MIT-0

set -euxo pipefail

install_args=()

while [ "${1:-}" != "" ]; do
  case "$1" in
    --package-url)
      shift
      if [[ $# -eq 0 ]]; then
        echo 'No argument specified for --package-url' >&2
        exit 1
      fi
      install_args+=(--package-url $1)
      ;;
    *)
      echo 'Invalid command line argument' >&2
      exit 1
  esac
  shift
done

echo 'APT::Acquire::Retries "4";' > /etc/apt/apt.conf.d/80-acquire-retries
echo 'APT::Get::Assume-Yes "true";' > /etc/apt/apt.conf.d/90-get-assume-yes

export DEBIAN_FRONTEND='noninteractive'

setup/install_prereqs "${install_args[@]}"
