#!/bin/bash
# SPDX-License-Identifier: MIT-0

set -euxo pipefail

"python$PYTHON_VERSION" --version
"python$PYTHON_VERSION" -m venv env

source env/bin/activate
pip install drake

python3 -c 'import pydrake.all; print(pydrake.__file__)'

cd src
python3 particle_test.py

cd ..
deactivate
rm -rf env src/__pycache__
