#!/bin/bash

# Copyright (c) 2018, Massachusetts Institute of Technology
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of the copyright holder nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

set -eux

# https://github.com/travis-ci/travis-ci/issues/8552
brew update

# https://github.com/travis-ci/travis-ci/issues/8826
brew cask uninstall oclint

# Clean up any numpy/scipy residuals
# https://github.com/travis-ci/travis-ci/issues/6688
# https://github.com/RobotLocomotion/drake-shambhala/pull/102#issuecomment-383708589
rm -f /usr/local/bin/f2py
rm -rf /usr/local/lib/python2.7/site-packages/numpy-*-py2.7.egg-info
rm -rf /usr/local/lib/python2.7/site-packages/numpy/
rm -rf /usr/local/lib/python2.7/site-packages/scipy-*-py2.7.egg-info
rm -rf /usr/local/lib/python2.7/site-packages/scipy/

# https://github.com/Homebrew/homebrew-core/issues/26358
brew upgrade python || true

# https://github.com/Homebrew/homebrew-core/issues/24978
brew uninstall --force mercurial
brew install mercurial

./scripts/continuous_integration/common/mac
