#!/bin/bash
# SPDX-License-Identifier: MIT-0

set -euxo pipefail

./scripts/continuous_integration/common/drake_bazel_external
./scripts/continuous_integration/common/drake_cmake_external
./scripts/continuous_integration/common/drake_catkin_installed
./scripts/continuous_integration/common/drake_cmake_installed
