#!/bin/bash
# SPDX-License-Identifier: MIT-0

set -euxo pipefail

sudo ./scripts/setup/linux/ubuntu/jammy/install_prereqs

cat > "${HOME}/.bazelrc" << EOF
startup --output_user_root=${WORKSPACE}/_bazel_${USER}
test --color=yes
test --keep_going
EOF
