#!/bin/bash
# SPDX-License-Identifier: MIT-0

set -euxo pipefail

sudo ./scripts/continuous_integration/common/linux_ubuntu_jammy

cat > "${HOME}/.bazelrc" << EOF
startup --output_user_root=${WORKSPACE}/_bazel_${USER}
test --color=yes
test --keep_going
EOF
