# -*- python -*-

# This file marks a workspace root for the Bazel build system. see
# http://bazel.io/ .

# To temporarily use a local copy of a github_archive, within this file add a
# local_repository_archive argument to its github_archive macro call, e.g.:
#
# github_archive(
#     name = "foobar",
#     local_repository_override = "/path/to/local/foo/bar",
#     repository = "foo/bar",
#     commit = "0123456789abcdef0123456789abcdef01234567",
#     sha256 = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
# )

workspace(name = "bazel_drake_side_by_side")

load("//tools:bitbucket.bzl", "bitbucket_archive")
load("//tools:github.bzl", "github_archive")

##############################################################################
# The Drakeverse
##############################################################################

github_archive(
    name = "drake",
    repository = "RobotLocomotion/drake",
    commit = "90f71bf4990ac2b9f9216868c991278c0d7869b4",
    sha256 = "62feb7694279dd58794283e20ed45ffef9871c2f1d8cb3961c1e72823f034f3a",
)

github_archive(
    name = "fmt",
    repository = "fmtlib/fmt",
    commit = "3.0.1",
    build_file = "tools/drake/fmt.BUILD",
    sha256 = "dce62ab75a161dd4353a98364feb166d35e7eea382169d59d9ce842c49c55bad",
)

github_archive(
    name = "protobuf",
    repository = "google/protobuf",
    commit = "v3.1.0",
    sha256 = "0a0ae63cbffc274efb573bdde9a253e3f32e458c41261df51c5dbc5ad541e8f7",
)

github_archive(
    name = "spdlog",
    repository = "gabime/spdlog",
    commit = "43a4048b92ef5b7eff6dc637a621c7da3a41d194",
    build_file = "tools/drake/spdlog.BUILD",
    sha256 = "5166c036eacd625b86f725bfba356547e0bc497232649662c61cde7b1b423292",
)

bitbucket_archive(
    name = "eigen",
    repository = "eigen/eigen",
    # N.B. See #5785; do your best not to have to bump this to a newer commit.
    commit = "3.3.3",
    sha256 = "94878cbfa27b0d0fbc64c00d4aafa137f678d5315ae62ba4aecddbd4269ae75f",
    build_file = "tools/drake/eigen.BUILD",
    strip_prefix = "eigen-eigen-67e894c6cd8f",
)
