#!/bin/bash
# SPDX-License-Identifier: MIT-0

set -euxo pipefail

# Use what we downloaded to drake_bazel_external/drake,
# rather than the URL to the latest Drake master branch
# found in drake_bazel_external/MODULE.bazel.
override_module_flag="--override_module=drake=drake"

# Suppress compiler warnings for gcc 13 as suggested in
# drake_bazel_external/.bazelrc.
gcc_flag="--@drake//tools/cc_toolchain:compiler_major="
gcc_flag="${gcc_flag}$(gcc -dumpversion | cut -d. -f1)"

bazel version
bazel test "${gcc_flag}" "${override_module_flag}" //...
