#!/bin/bash
# SPDX-License-Identifier: MIT-0

set -euxo pipefail

# Use what we downloaded to drake_bazel_external/drake,
# rather than the URL to the latest Drake master branch
# found in drake_bazel_external/MODULE.bazel.
override_module_flag="--override_module=drake=drake"

bazel version
bazel test "${override_module_flag}" //...
