#!/bin/bash
# SPDX-License-Identifier: MIT-0

set -euxo pipefail

cat <<EOF > "user.bazelrc"
# Use what we downloaded to drake_bazel_external/drake,
# rather than the URL to the latest Drake master branch
# found in drake_bazel_external/MODULE.bazel.
build --override_module=drake=drake

# Pass along the compiler version to Drake
# (as suggested in drake_bazel_external/.bazelrc).
build --@drake//tools/cc_toolchain:compiler_major=$(gcc -dumpversion)

# Use force_pic to speed up the build, as this only runs on Ubuntu
# (as suggested in drake_bazel_external/.bazelrc).
build --force_pic=yes
EOF

bazel version
bazel test //...
