#!/bin/bash
# SPDX-License-Identifier: MIT-0

set -euxo pipefail

# CI setup
sudo ./.github/ubuntu_setup

# Download the drake source
mkdir ~/drake_install
wget -O drake.tar.gz \
  https://github.com/RobotLocomotion/drake/archive/master.tar.gz
trap 'rm -f drake.tar.gz' EXIT
tar -xf drake.tar.gz -C ~/drake_install

# Install the source prereqs
sudo ~/drake_install/drake-master/setup/ubuntu/install_prereqs.sh
