# SPDX-License-Identifier: MIT-0

---
name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:
    inputs:
      linux_noble_wheel:
        description: 'Drake linux-noble-*-wheel-*-release Python 3.12 artifact URL'
        required: false
      mac_arm_sequoia_wheel:
        description: 'Drake mac-arm-sequoia-*-wheel-*-release Python 3.14 artifact URL'
        required: false
concurrency:
  # Cancel previous CI runs when additional commits are added to a pull request.
  # This will not cancel CI runs associated with `schedule` or `push`.
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  macos_sequoia_arm_pip:
    name: macos sequoia 15 arm
    runs-on: macos-15
    env:
      PYTHON_VERSION: '3.14'
    steps:
      - name: checkout
        uses: actions/checkout@v6
      # Note that in the requirements.txt,
      # we find the latest "compatible release" of drake
      # using ~=. This means that, with the caching disabled,
      # poetry will find the most recent version of drake
      # that uses the same major number. With the caching enabled, however,
      # setup-python will use the version of drake that is in the cache,
      # until the requirements.txt file is updated
      # (see the cache-dependency-path argument below).
      # We update the requirements.txt file monthly after a new minor
      # version of drake using automated renovate PRs.
      # Note that between a new minor release of drake and the renovate
      # PR for that release being merged in, setup-python will
      # pull in the older version of drake.
      - name: python setup
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      - name: venv setup and install
        working-directory: drake_pip
        run: |
          args=(--python-version $PYTHON_VERSION)
          if [[ '${{ github.event.inputs.mac_arm_sequoia_wheel }}' != '' ]]; then
            args+=(--wheel-url ${{ github.event.inputs.mac_arm_sequoia_wheel }})
          fi
          setup/setup_env "${args[@]}"
        shell: zsh -eufo pipefail {0}
      - name: pip build and test
        working-directory: drake_pip
        run: .github/ci_build_test
        shell: zsh -efuo pipefail {0}
  ubuntu_noble_pip:
    name: ubuntu 24.04 noble
    runs-on: ubuntu-latest
    container: ubuntu:noble
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: pip setup
        working-directory: drake_pip
        run: |
          args=()
          if [[ '${{ github.event.inputs.linux_noble_wheel }}' != '' ]]; then
            args+=(--wheel-url ${{ github.event.inputs.linux_noble_wheel }})
          fi
          .github/ubuntu_setup "${args[@]}"
        shell: bash
      - name: pip build and test
        working-directory: drake_pip
        run: .github/ci_build_test
        shell: bash
