#!/bin/bash
# SPDX-License-Identifier: MIT-0

set -euxo pipefail

poetry --version
"python$PYTHON_VERSION" --version
poetry init -n --python "~$PYTHON_VERSION"
poetry env use $PYTHON_VERSION

poetry add drake
eval $(poetry env activate)

python3 -c 'import pydrake.all; print(pydrake.__file__)'

cd src
python3 particle_test.py

cd ..
deactivate
rm -rf src/__pycache__
