#!/bin/bash
# SPDX-License-Identifier: MIT-0

set -euxo pipefail

poetry --version

poetry init -n
poetry add drake
eval $(poetry env activate)

python3 -c 'import pydrake.all; print(pydrake.__file__)'

python3 src/particle_test.py

deactivate
rm -rf src/__pycache__