#!/bin/bash
# SPDX-License-Identifier: MIT-0

set -euxo pipefail

echo 'APT::Acquire::Retries "4";' > /etc/apt/apt.conf.d/80-acquire-retries
echo 'APT::Get::Assume-Yes "true";' > /etc/apt/apt.conf.d/90-get-assume-yes

export DEBIAN_FRONTEND='noninteractive'

sudo apt-get install --no-install-recommends $(cat <<EOF
  pipx
EOF
)

pipx install poetry