# SPDX-License-Identifier: MIT-0

---
name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:
    inputs:
      linux_noble_wheel:
        description: 'Drake linux-noble-*-wheel-*-release Python 3.12 artifact URL'
        required: false
      mac_arm_sequoia_wheel:
        description: 'Drake mac-arm-sequoia-*-wheel-*-release Python 3.14 artifact URL'
        required: false
concurrency:
  # Cancel previous CI runs when additional commits are added to a pull request.
  # This will not cancel CI runs associated with `schedule` or `push`.
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  macos_sequoia_arm_poetry:
    name: macos sequoia 15 arm
    runs-on: macos-15
    env:
      PYTHON_VERSION: '3.14'
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: install poetry
        working-directory: drake_poetry
        run: .github/setup
      # Note that in the pyproject.toml,
      # we find the latest "compatible release" of drake
      # using ~=. This means that, with the caching disabled,
      # poetry will find the most recent version of drake
      # that uses the same major number. With the caching enabled, however,
      # setup-python will use the version of drake that is in the cache,
      # until the pyproject.toml file is updated
      # (see the cache-dependency-path argument below).
      # We update the pyproject.toml file monthly after a new minor
      # version of drake using automated renovate PRs.
      # Note that between a new minor release of drake and the renovate
      # PR for that release being merged in, setup-python will
      # pull in the older version of drake.
      - name: python setup
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'poetry'
          cache-dependency-path: 'drake_poetry/pyproject.toml'
      - name: poetry setup
        working-directory: drake_poetry
        run: |
          args=(--python-version $PYTHON_VERSION)
          if [[ '${{ github.event.inputs.mac_arm_sequoia_wheel }}' != '' ]]; then
            args+=(--wheel-url ${{ github.event.inputs.mac_arm_sequoia_wheel }})
          fi
          setup/install_prereqs "${args[@]}"
        shell: zsh -efuo pipefail {0}
      - name: poetry test
        working-directory: drake_poetry
        run: .github/ci_build_test
        shell: zsh -efuo pipefail {0}
  ubuntu_noble_poetry:
    name: ubuntu 24.04 noble
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: '3.12'
    container: ubuntu:noble
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: install poetry
        working-directory: drake_poetry
        # When poetry is installed, the update to the PATH
        # environment variable does not persist between steps on
        # GHA. Thus, we update the path after installing.
        run: |
          .github/setup
          PIPX_BIN=$(pipx environment --value PIPX_BIN_DIR)
          echo "$PIPX_BIN" >> $GITHUB_PATH
      - name: python setup
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'poetry'
          cache-dependency-path: 'drake_poetry/pyproject.toml'
      - name: poetry setup and test
        working-directory: drake_poetry
        run: |
          source $HOME/.profile
          args=()
          if [[ '${{ github.event.inputs.linux_noble_wheel }}' != '' ]]; then
            args+=(--wheel-url ${{ github.event.inputs.linux_noble_wheel }})
          fi
          setup/install_prereqs "${args[@]}"
          .github/ci_build_test
        shell: bash
