# SPDX-License-Identifier: MIT-0

---
name: ci
on:
  workflow_call:

jobs:
  ubuntu_jammy_cmake_installed:
    name: ubuntu 22.04 jammy cmake installed
    runs-on: ubuntu-latest
    container: ubuntu:jammy
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup
        run: ./drake_cmake_installed/.github/ubuntu_setup
        shell: bash
      - name: cmake_installed build and test
        run: ./drake_cmake_installed/.github/ci_build_test
        shell: bash
