# SPDX-License-Identifier: MIT-0

---
name: stale
on:
  schedule:
    - cron: '30 1 * * *'
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-issue-close: -1
          days-before-issue-stale: -1
          days-before-pr-close: 14
          days-before-pr-stale: 180
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-label: 'result: stale'
          stale-pr-message: >
            Thank you for your contribution. This pull request has been open for
            180 days without activity and so is considered stale. It will be
            automatically closed in 14 days unless you comment or remove the
            "result: stale" label.
